name: Snake generator

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # run every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Mubashira991
          outputs:
            dist/github-snake-dark.svg
        env:
          COLOR_SNAKE: '#f97316'        
          COLOR_DOTS: '#94a3b8,#f87171'

      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
